
const dependencyPlatforms = {
    "@cdm-logger/server": 'server',
    "@adminide-stack/utils": 'server',
    "@adminide-stack/core": 'nodll',
    "@adminide-stack/account-api-browser": "noddl",
    "@adminide-stack/docker-api-browser": "noddl",
    "@adminide-stack/frontend-module": "noddl",
    "@adminide-stack/git-api-browser": "noddl",
    "@adminide-stack/monocular-api-browser": "noddl",
    "@adminide-stack/react-shared-components": "noddl",
    "@adminide-stack/subscription-stripe-browser": "noddl",
    "@adminide-stack/user-auth0-browser": "noddl",
    "@adminide-stack/subscription-stripe-browser": "noddl",
    "@adminide-stack/user-auth0-server": "noddl",
    "@adminide-stack/workspaces-browser": "noddl",
    "@container-stack/ssh-keygen-server-module": "noddl",
    "@common-stack/cache-api-server": "noddl",
    "bunyan": 'server',
    "export-dir": 'server',
    "express": 'server',
    'body-parser': 'server',
    express: 'server',
    'apollo-server-express': 'server',
    'graphql-subscriptions': 'server',
    'graphql-tools': 'server',
    "graphql-tag": ['server', 'web'],
    'immutability-helper': ['ios', 'android', 'web'],
    'isomorphic-fetch': 'server',
    knex: 'server',
    mysql2: 'server',
    persistgraphql: ['server', 'web'],
    "graphql-nats-subscriptions": 'server',
    "graphql-server-core": 'server',
    "apollo-server-express": 'server',
    "graphql-tools": 'server',
    "helmet": 'server',
    "hemera-joi": 'server',
    "hemera-plugin": 'server',
    "hemera-safe-promises": 'server',
    "hemera-sql-store": 'server',
    "hemera-zipkin": 'server',
    "inversify": 'server',
    "morgan": 'server',
    "nats": 'server',
    "nats-hemera": 'server',
    "nconf": 'server',
    "node-pre-gyp": 'server',
    "prop-types": 'web',
    "ramda": ['web', 'server'],
    "redis": "noddl",
    "ioredis": "noddl",
    "reflect-metadata": 'server',
    "sequelize": 'server',
    'react-native': ['ios', 'android'],
    'react-navigation': ['ios', 'android'],
    'serialize-javascript': 'server',
    'source-map-support': 'server',
    'styled-components': ['server', 'web'],
    'subscriptions-transport-ws': ['ios', 'android', 'web'],
    'ws': ['server']
};

module.exports = { dependencyPlatforms };