export enum WorkspaceClientRequests {
    WORKSPACE_CREATE_REQ = 'WORKSPACE_CREATE_REQ',
    WORKSPACE_REMOVE_REQ = 'WORKSPACE_REMOVE_REQ',
    WORKSPACE_START_REQ = 'WORKSPACE_START_REQ',
    WORKSPACE_STOP_REQ = 'WORKSPACE_STOP_REQ',
    WORKSPACE_UPDATE_REQ = 'WORKSPACE_UPDATE_REQ',
}
