query GitRepositories($input: IGitServiceInput!){
  getGitRepositories(input: $input) {
    id
    url
    name
    path
    owner
    private
    description
    clone {
        ssh
        https
    }
  }
}