fragment WorkspaceInfo on Workspace {
        id
        name
        language
        status
        description
        icon_url
        spec {
            cpu
            ram
            hdd
        }
}