mutation createTeam($request: ITeamCreationRequest!) {
    createTeam(request: $request) {
        _id
        name
        tags
        orgId
        createdAt
        updatedAt
        description
    }
}